### ISSUE TITLE
ValueError converting cif files created in Mercury

### ISSUE THREAD

**Issue by mpougin** [danieleongari/manage_crystal#6]
Mercury creates cifs in a format, where numbers in brackets are included in the atom position (see attached example, I am not sure what these numbers tell). When I try to convert it and remove overlapping atoms with manage crystal I get the following error:

`Traceback (most recent call last):                                                                                                               
File "/home/miriam/anaconda3/envs/aiida1/bin/manage_crystal", line 199, in <module>                                                                                           crys = parse_from_filepath(args.inputfile, args.tm)                                                                                                                       File "/home/miriam/anaconda3/envs/aiida1/lib/python3.6/site-packages/manage_crystal/file_parser.py", line 36, in parse_from_filepath                                          
crys = parse_cif(file)                                                                                                                                                   
File "/home/miriam/anaconda3/envs/aiida1/lib/python3.6/site-packages/manage_crystal/file_parser.py", line 167, in parse_cif                                                   float(data[data_order_dic["_atom_site_fract_x"]]),                                                                                                                      ValueError: could not convert string to float: '0.22437(8)' `
[CPM-80-Zn_2.txt](https://github.com/danieleongari/manage_crystal/files/5879546/CPM-80-Zn_2.txt)

**Comment by danieleongari** [comment]
Fixed in https://github.com/danieleongari/manage_crystal/commit/8ba1e72aec9876bee09170ae38590521d2734eff
Of course You may still have problems related to the non-P1 sym space, but I assume you need manage_crystal to do son manual operations.
